# Generated by Django 5.2.5 on 2025-08-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.CharField(default='/', help_text='Путь к папке, например: /folder1/subfolder/', max_length=500),
        ),
    ]
