# Generated by Django 5.2.5 on 2025-08-17 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_folder_parent_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания папки'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания заметки'),
        ),
    ]
