# Generated by Django 5.2.7 on 2026-07-26 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_board_position_taskboardcolumn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.CreateModel(
            name='PushEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('daily_summary', 'Daily summary'), ('deadline', 'Deadline')], max_length=32)),
                ('dedupe_key', models.CharField(max_length=191, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_events', to='api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_push_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('endpoint_hash', models.CharField(max_length=64, unique=True)),
                ('p256dh', models.CharField(max_length=512)),
                ('auth', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_web_push_subscription',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PushDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('retry', 'Retry'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='api.pushevent')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts', to='api.webpushsubscription')),
            ],
            options={
                'db_table': 'api_push_delivery_attempt',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='api_push_de_status_388c35_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'subscription_hash'), name='unique_push_event_subscription')],
            },
        ),
    ]
