# Generated by Django 5.2.7 on 2025-11-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_folder_user_note_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.folder')),
                ('note', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.note')),
            ],
        ),
    ]
