# Generated by Django 5.2.7 on 2025-11-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.folder'),
            preserve_default=False,
        ),
    ]
