# Generated by Django 5.2.7 on 2026-06-12 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_task_checklist_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='note_from',
            field=models.ForeignKey(help_text='Source note', on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='api.note'),
        ),
        migrations.AlterField(
            model_name='link',
            name='note_to',
            field=models.ForeignKey(help_text='Target note', on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='api.note'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Parent folder note', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_folder',
            field=models.BooleanField(default=False, help_text='True if this note is a folder'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='api_profile',
        ),
    ]
