export const routes = {
  home: '/',
  auth: '/auth',
  registration: '/registration',
  privacy: '/privacy',
  terms: '/terms',
  notesOnline: '/notes-online',
  tasksAndNotes: '/tasks-and-notes',
  weeklyPlanner: '/weekly-planner',
  knowledgeGraph: '/knowledge-graph',
  markdownNotes: '/markdown-notes',
  faq: '/faq',
  notes: '/notes',
  folders: '/folders',
  profile: '/profile',
  tasks: '/tasks',
};
